package de.unibi.agbi.biodwh2.chebi.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import de.unibi.agbi.biodwh2.core.model.graph.GraphBooleanProperty;
import de.unibi.agbi.biodwh2.core.model.graph.GraphNodeLabel;
import de.unibi.agbi.biodwh2.core.model.graph.GraphProperty;

@JsonPropertyOrder({
        "id", "compound_id", "formula", "charge", "mass", "monoisotopic_mass", "status_id", "structure_id",
        "is_autogenerated"
})
@GraphNodeLabel("ChemicalData")
public class ChemicalData {
    @JsonProperty("id")
    @GraphProperty("id")
    public Integer id;
    @JsonProperty("compound_id")
    public Integer compoundId;
    @JsonProperty("formula")
    @GraphProperty("formula")
    public String formula;
    @JsonProperty("charge")
    @GraphProperty("charge")
    public Integer charge;
    @JsonProperty("mass")
    @GraphProperty("mass")
    public String mass;
    @JsonProperty("monoisotopic_mass")
    @GraphProperty("monoisotopic_mass")
    public String monoisotopicMass;
    @JsonProperty("status_id")
    public Integer statusId;
    @JsonProperty("structure_id")
    public Integer structureId;
    @JsonProperty("is_autogenerated")
    @GraphBooleanProperty("is_autogenerated")
    public String isAutogenerated;
}
