package de.unibi.agbi.biodwh2.core.io.biopax;

import com.fasterxml.jackson.annotation.JsonProperty;

public enum ControlType {
    @JsonProperty("ACTIVATION") ACTIVATION,
    @JsonProperty("ACTIVATION_ALLOSTERIC") ACTIVATION_ALLOSTERIC,
    @JsonProperty("ACTIVATION_NONALLOSTERIC") ACTIVATION_NONALLOSTERIC,
    @JsonProperty("INHIBITION") INHIBITION,
    @JsonProperty("INHIBITION_ALLOSTERIC") INHIBITION_ALLOSTERIC,
    @JsonProperty("INHIBITION_COMPETITIVE") INHIBITION_COMPETITIVE,
    @JsonProperty("INHIBITION_IRREVERSIBLE") INHIBITION_IRREVERSIBLE,
    @JsonProperty("INHIBITION_NONCOMPETITIVE") INHIBITION_NONCOMPETITIVE,
    @JsonProperty("INHIBITION_OTHER") INHIBITION_OTHER,
    @JsonProperty("INHIBITION_UNCOMPETITIVE") INHIBITION_UNCOMPETITIVE
}
