package de.unibi.agbi.biodwh2.core.io.obo;

/**
 * header-frame ::= { header-clause nl* }
 * header-clause ::= format-version-TVP
 *         | data-version-TVP
 *         | date-Tag  DD:MM:YYYY ws hh:mm
 *         | saved-by-TVP
 *         | auto-generated-by-TVP
 *         | import-Tag  IRI | filepath
 *         | subsetdef-Tag  Subset-ID ws QuotedString
 *         | synonymtypedef-Tag  SynonymType-ID ws QuotedString
 *              [  SynonymScope ]
 *         | default-namespace-Tag  OBONamespace
 *         | idspace-Tag IDPrefix ws IRI
 *             [ ws QuotedString ]
 *         | treat-xrefs-as-equivalent-Tag IDPrefix
 *         | treat-xrefs-as-genus-differentia-Tag IDPrefix ws Rel-ID ws Class-ID
 *         | treat-xrefs-as-reverse-genus-differentia-Tag IDPrefix ws Rel-ID ws Class-ID
 *         | treat-xrefs-as-relationship-Tag IDPrefix Rel-ID
 *         | treat-xrefs-as-is_a-Tag IDPrefix
 *         | treat-xrefs-as-has-subclass-Tag IDPrefix
 *         | property_value-Tag Relation-ID ( QuotedString XSD-Type | ID ) {WhiteSpaceChar} [ QualifierBlock ] {WhiteSpaceChar} [ HiddenComment ]
 *         | remark-TVP
 *         | ontology-TVP
 *         | owl-axioms-TVP
 *         | UnreservedToken ':'  [  ws ] UnquotedString
 */
@SuppressWarnings("unused")
public final class OboHeader extends OboEntry {
    OboHeader() {
        super(null);
    }

    public String getFormatVersion() {
        return getFirst("format-version");
    }

    public String getDataVersion() {
        return getFirst("data-version");
    }

    public String getDate() {
        return getFirst("date");
    }

    public String getSavedBy() {
        return getFirst("saved-by");
    }

    public String getAutoGeneratedBy() {
        return getFirst("auto-generated-by");
    }

    public String getDefaultNamespace() {
        return getFirst("default-namespace");
    }

    public String getRemark() {
        return getFirst("remark");
    }

    public String getOntology() {
        return getFirst("ontology");
    }
}
