package de.unibi.agbi.biodwh2.core.io.obo;

/**
 * OBO Header definition
 * <p/>
 * http://purl.obolibrary.org/obo/oboformat/spec.html#3.2
 *
 * synonymtypedef-Tag  SynonymType-ID ws QuotedString
 *    [  SynonymScope ]
 * idspace-Tag IDPrefix ws IRI
 *   [ ws QuotedString ]
 * treat-xrefs-as-equivalent-Tag IDPrefix
 * treat-xrefs-as-genus-differentia-Tag IDPrefix ws Rel-ID ws Class-ID
 * treat-xrefs-as-reverse-genus-differentia-Tag IDPrefix ws Rel-ID ws Class-ID
 * treat-xrefs-as-relationship-Tag IDPrefix Rel-ID
 * treat-xrefs-as-is_a-Tag IDPrefix
 * treat-xrefs-as-has-subclass-Tag IDPrefix
 * property_value-Tag Relation-ID ( QuotedString XSD-Type | ID ) {WhiteSpaceChar} [ QualifierBlock ] {WhiteSpaceChar} [ HiddenComment ]
 * owl-axioms-TVP
 * UnreservedToken ':'  [  ws ] UnquotedString
 */
public final class OboHeader extends OboStructure {
    OboHeader() {
        super();
    }

    /**
     * cardinality 0-1
     * @return TVP
     */
    public String getFormatVersion() {
        return getFirst("format-version");
    }

    /**
     * cardinality *
     * @return TVP[]
     */
    public String[] getDataVersions() {
        return get("data-version");
    }

    /**
     * cardinality *
     * @return (IRI | filepath)[]
     */
    public String[] getImports() {
        return get("import");
    }

    /**
     * cardinality *
     * @return (Subset-ID ws QuotedString)[]
     */
    public String[] getSubsetDefs() {
        return get("subsetdef");
    }

    /**
     * cardinality 0-1
     * @return DD:MM:YYYY ws hh:mm
     */
    public String getDate() {
        return getFirst("date");
    }

    /**
     * cardinality 0-1
     * @return TVP
     */
    public String getSavedBy() {
        return getFirst("saved-by");
    }

    /**
     * cardinality 0-1
     * @return TVP
     */
    public String getAutoGeneratedBy() {
        return getFirst("auto-generated-by");
    }

    /**
     * cardinality 0-1
     * @return OBONamespace
     */
    public String getDefaultNamespace() {
        return getFirst("default-namespace");
    }

    /**
     * cardinality *
     * @return TVP[]
     */
    public String[] getRemarks() {
        return get("remark");
    }

    /**
     * cardinality 0-1
     * @return TVP
     */
    public String getOntology() {
        return getFirst("ontology");
    }
}
