name: Java CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        java-package: jdk+fx
    - name: print Java version
      run: java -version
    - name: Build with Maven
      run: mvn package --file src/pom.xml
